# Generated by Django 4.1.7 on 2023-03-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_product_description_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
